<!--
document.write("<div id='menuHead' class='menuStyle'>");
document.write("<p class='text0'>");
document.write("<a id='menuHead1' class='menuLink' href='tw.html' onmouseout='t = 1; delayHide()' onmouseover='popMenu(1)'>TW&nbsp;Home</a>&nbsp;&nbsp;|&nbsp;&nbsp;");
document.write("<a id='menuHead2' class='menuLink' href='#' onmouseout='t = 1; delayHide()' onmouseover='popMenu(2)'>Test1</a>&nbsp;&nbsp;|&nbsp;&nbsp;");
document.write("<a id='menuHead3' class='menuLink' href='#' onmouseout='t = 1; delayHide()' onmouseover='popMenu(3)'>Test2</a>&nbsp;&nbsp;|&nbsp;&nbsp;");
document.write("<a id='menuHead4' class='menuLink' href='#' onmouseout='t = 1; delayHide()' onmouseover='popMenu(4)'>Test3</a>&nbsp;&nbsp;|");
document.write("</p>");
document.write("</div>");
document.write("<div id='menu1' class='menuStyle'>");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='#'></a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='#'></a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='#'></a><br />");
document.write("</div>");
document.write("<div id='menu2' class='menuStyle'>");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twco10s.html'>Course Outline</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twwds.html'>Web Design Specs</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twwdr.html'>Web Design Resources</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twxhtml.html'>XHTML Guidelines</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='http://rpilms.rpi.edu/webct/entryPageIns.dowebct' target='blank'>Class Readings</a><br />");
document.write("</div>");
document.write("<div id='menu3' class='menuStyle'>");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twpwp.html'>Professional Web Page</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twom.html'>Organizational Memo</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twpow.html'>Organization Web</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twpsr.html'>Problem-Solving Report</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twip.html'>Product-Support Web</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twip.html'>Decision-Making Report</a><br />");
document.write("</div>");
document.write("<div id='menu4' class='menuStyle'>");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twwp.html'>TW Web Page</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twie.html'>Image&nbsp;Editing</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twcss1.html'>Style Sheets 1</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twwad.html'>Web Authoring</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twcss2.html'>Style Sheets 2</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twms.html'>Menu Systems</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twip.html'>Style Sheets 3</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twip.html'>Hypertext Systems 1</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twip.html'>Hypertext Systems 2</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twip.html'>Ajax Page Display</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='twip.html'>Ajax Page Preview</a><br />");
document.write("<a class='menuLink' onmouseout='t = 1; delayHide()' onmouseover='t = 2;' onclick='t = 0; delayHide();' href='resources.html'>Web&nbsp;Resources</a><br />");
document.write("</div>");
//-->
 
